/* Includes */

#include "lib_types.h"
#include "lib_utils.h"

#include "HW_TIM.h"
// HAL types in the stm32g4 macro bodies (TIM_HandleTypeDef, TIM1,
// TIM_CHANNEL_1, ...) come transitively through HW_TIM.h, which on the
// embedded target resolves to stm32g4/HW_TIM.h.

// Auto-generated CubeMX-derived field values, re-generated by
// tools/cubemx_to_channels.py (called from
// tools/convert_cubemx_to_canonical.sh) whenever the .ioc changes. Each
// HW_TIM_CUBEMX_TIMn expands to the right per-target body via a
// BUILD_TARGET selection inside the header, so the mapping below is
// target-uniform. The matching clock-enable + output-pin AF live in the
// generated stm32g4xx_hal_msp.c (HAL_TIM_Base_MspInit / HAL_TIM_MspPostInit).
#include "HW_TIM_channels.cubemx.h"

// NOTE: TIM1 currently has no dead-time, break input, or TRGO configured in
// the .ioc — add them (and set the PWM period for the target carrier
// frequency) in CubeMX, then re-run the converter, before driving the
// gate-driver bridge.

/* Private Data Definitions */

const HW_TIM_channelConfig_S HW_TIM_channelConfig[HW_TIM_CHANNEL_COUNT] =
{
    [HW_TIM_CHANNEL_1] = { HW_TIM_CUBEMX_TIM1 },   // 3-phase motor PWM
    [HW_TIM_CHANNEL_2] = { HW_TIM_CUBEMX_TIM2 },   // 1 us free-running time base
};

const HW_TIM_config_S HW_TIM_config =
{
    .channels    = HW_TIM_channelConfig,
    .numChannels = COUNTOF(HW_TIM_channelConfig),
};
