// AUTO-GENERATED by tools/cubemx_to_channels.py from
// sw/fw/stm32cube/g4/Core/Src/main.c. Do not hand-edit.
//
// Re-generate via: tools/convert_cubemx_to_canonical.sh
//
// This file holds macros containing CubeMX-derived field values.
// The hand-written HW_*_channels.c references them inside its
// struct initializers; user-managed fields (triggerMode, vref,
// injectedInputs, ...) live there too, outside the macro
// expansions.

#ifndef HW_TIM_CHANNELS_CUBEMX_H
#define HW_TIM_CHANNELS_CUBEMX_H

// Each timer exposes a per-target body (HW_TIM_CUBEMX_G4_TIMn /
// HW_TIM_CUBEMX_SIM_TIMn) and a BUILD_TARGET-selected alias
// (HW_TIM_CUBEMX_TIMn) used by HW_TIM_channels.c. lib_build.h
// supplies the BUILD_TARGET_* constants the selection compares.
#include "lib_build.h"

// ----- TIM1 -----

#define HW_TIM_CUBEMX_INIT_TIM1 \
    .Prescaler         = 0, \
    .CounterMode       = TIM_COUNTERMODE_CENTERALIGNED1, \
    .Period            = 3599, \
    .ClockDivision     = TIM_CLOCKDIVISION_DIV1, \
    .RepetitionCounter = 1, \
    .AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE,

#define HW_TIM_CUBEMX_OC_TIM1 \
    [0] = \
    { \
        .enabled       = true, \
        .channel       = TIM_CHANNEL_1, \
        .complementary = true, \
        .oc = \
        { \
            .OCMode       = TIM_OCMODE_PWM1, \
            .Pulse        = 0, \
            .OCPolarity   = TIM_OCPOLARITY_HIGH, \
            .OCNPolarity  = TIM_OCNPOLARITY_HIGH, \
            .OCFastMode   = TIM_OCFAST_DISABLE, \
            .OCIdleState  = TIM_OCIDLESTATE_RESET, \
            .OCNIdleState = TIM_OCNIDLESTATE_RESET, \
        }, \
    }, \
    [1] = \
    { \
        .enabled       = true, \
        .channel       = TIM_CHANNEL_2, \
        .complementary = true, \
        .oc = \
        { \
            .OCMode       = TIM_OCMODE_PWM1, \
            .Pulse        = 0, \
            .OCPolarity   = TIM_OCPOLARITY_HIGH, \
            .OCNPolarity  = TIM_OCNPOLARITY_HIGH, \
            .OCFastMode   = TIM_OCFAST_DISABLE, \
            .OCIdleState  = TIM_OCIDLESTATE_RESET, \
            .OCNIdleState = TIM_OCNIDLESTATE_RESET, \
        }, \
    }, \
    [2] = \
    { \
        .enabled       = true, \
        .channel       = TIM_CHANNEL_3, \
        .complementary = true, \
        .oc = \
        { \
            .OCMode       = TIM_OCMODE_PWM1, \
            .Pulse        = 0, \
            .OCPolarity   = TIM_OCPOLARITY_HIGH, \
            .OCNPolarity  = TIM_OCNPOLARITY_HIGH, \
            .OCFastMode   = TIM_OCFAST_DISABLE, \
            .OCIdleState  = TIM_OCIDLESTATE_RESET, \
            .OCNIdleState = TIM_OCNIDLESTATE_RESET, \
        }, \
    },

#define HW_TIM_CUBEMX_BDT_TIM1 \
    .OffStateRunMode  = TIM_OSSR_ENABLE, \
    .OffStateIDLEMode = TIM_OSSI_ENABLE, \
    .LockLevel        = TIM_LOCKLEVEL_OFF, \
    .DeadTime         = 0, \
    .BreakState       = TIM_BREAK_ENABLE, \
    .BreakPolarity    = TIM_BREAKPOLARITY_HIGH, \
    .BreakFilter      = 0, \
    .BreakAFMode      = TIM_BREAK_AFMODE_INPUT, \
    .Break2State      = TIM_BREAK2_DISABLE, \
    .Break2Polarity   = TIM_BREAK2POLARITY_HIGH, \
    .Break2Filter     = 0, \
    .Break2AFMode     = TIM_BREAK_AFMODE_INPUT, \
    .AutomaticOutput  = TIM_AUTOMATICOUTPUT_DISABLE,

#define HW_TIM_CUBEMX_BRKIN_TIM1 \
    [0] = \
    { \
        .enabled    = true, \
        .breakInput = TIM_BREAKINPUT_BRK, \
        .config = \
        { \
            .Source   = TIM_BREAKINPUTSOURCE_BKIN, \
            .Enable   = TIM_BREAKINPUTSOURCE_ENABLE, \
            .Polarity = TIM_BREAKINPUTSOURCE_POLARITY_LOW, \
        }, \
    },

#define HW_TIM_CUBEMX_MASTER_TIM1 \
    .MasterOutputTrigger  = TIM_TRGO_UPDATE, \
    .MasterOutputTrigger2 = TIM_TRGO2_RESET, \
    .MasterSlaveMode      = TIM_MASTERSLAVEMODE_DISABLE,

#define HW_TIM_CUBEMX_G4_TIM1 \
    .htim = \
    { \
        .Instance = TIM1, \
        .Init = { HW_TIM_CUBEMX_INIT_TIM1 }, \
    }, \
    .outputCompare = { HW_TIM_CUBEMX_OC_TIM1 }, \
    .configureBreakDeadTime = true, \
    .breakDeadTime = { HW_TIM_CUBEMX_BDT_TIM1 }, \
    .breakInputs = { HW_TIM_CUBEMX_BRKIN_TIM1 }, \
    .configureTrgo = true, \
    .master = { HW_TIM_CUBEMX_MASTER_TIM1 },

#define HW_TIM_CUBEMX_SIM_OC_TIM1 \
    [0] = { .enabled = true, .complementary = true, .compare = 0U, .inactiveLevel = 0U }, \
    [1] = { .enabled = true, .complementary = true, .compare = 0U, .inactiveLevel = 0U }, \
    [2] = { .enabled = true, .complementary = true, .compare = 0U, .inactiveLevel = 0U },

#define HW_TIM_CUBEMX_SIM_TIM1 \
    .channelNameStr   = "TIM1", \
    .prescaler        = 0U, \
    .period           = 3599U, \
    .counterWidthBits = 16U, \
    .countDir         = HW_TIM_COUNT_CENTER, \
    .outputCompare    = { HW_TIM_CUBEMX_SIM_OC_TIM1 }, \
    .configureBreakDeadTime = true, \
    .deadTime               = 0U, \
    .hasBreakInput          = true, \
    .configureTrgo          = true, \
    .trgoSource             = HW_TIM_TRGO_UPDATE,

// ----- TIM2 -----

#define HW_TIM_CUBEMX_INIT_TIM2 \
    .Prescaler         = 143, \
    .CounterMode       = TIM_COUNTERMODE_UP, \
    .Period            = 4294967295, \
    .ClockDivision     = TIM_CLOCKDIVISION_DIV1, \
    .AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE,

#define HW_TIM_CUBEMX_G4_TIM2 \
    .htim = \
    { \
        .Instance = TIM2, \
        .Init = { HW_TIM_CUBEMX_INIT_TIM2 }, \
    }, \
    .configureBreakDeadTime = false, \
    .configureTrgo = false,

#define HW_TIM_CUBEMX_SIM_TIM2 \
    .channelNameStr   = "TIM2", \
    .prescaler        = 143U, \
    .period           = 4294967295U, \
    .counterWidthBits = 32U, \
    .countDir         = HW_TIM_COUNT_UP, \
    .configureTrgo          = false,

// ----- target selection -----

#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
#define HW_TIM_CUBEMX_TIM1  HW_TIM_CUBEMX_G4_TIM1
#define HW_TIM_CUBEMX_TIM2  HW_TIM_CUBEMX_G4_TIM2
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
#define HW_TIM_CUBEMX_TIM1  HW_TIM_CUBEMX_SIM_TIM1
#define HW_TIM_CUBEMX_TIM2  HW_TIM_CUBEMX_SIM_TIM2
#else
#error "BUILD_TARGET must be BUILD_TARGET_STM32G4 or BUILD_TARGET_SIM"
#endif

#endif // HW_TIM_CHANNELS_CUBEMX_H
