// AUTO-GENERATED by tools/cubemx_to_channels.py from
// sw/fw/stm32cube/g4/Core/Src/main.c. Do not hand-edit.
//
// Re-generate via: tools/convert_cubemx_to_canonical.sh
//
// This file holds macros containing CubeMX-derived field values.
// The hand-written HW_*_channels.c references them inside its
// struct initializers; user-managed fields (triggerMode, vref,
// injectedInputs, ...) live there too, outside the macro
// expansions.

#ifndef HW_GPIO_CHANNELS_CUBEMX_H
#define HW_GPIO_CHANNELS_CUBEMX_H

#define HW_GPIO_CUBEMX_PINS_PORT_B \
    { \
        .Pin   = GPIO_PIN_2, \
        .Mode  = GPIO_MODE_OUTPUT_PP, \
        .Pull  = GPIO_NOPULL, \
        .Speed = GPIO_SPEED_FREQ_LOW, \
    }, \
    { \
        .Pin  = GPIO_PIN_10, \
        .Mode = GPIO_MODE_INPUT, \
        .Pull = GPIO_PULLUP, \
    }, \
    { \
        .Pin  = GPIO_PIN_6, \
        .Mode = GPIO_MODE_IT_RISING, \
        .Pull = GPIO_NOPULL, \
    },

#define HW_GPIO_CUBEMX_SIM_PINS_PORT_B \
    { .pin = 0x0004U, .mode = HW_GPIO_MODE_OUTPUT,           .pinNameStr = "PB2" }, \
    { .pin = 0x0400U, .mode = HW_GPIO_MODE_INPUT,            .pinNameStr = "PB10" }, \
    { .pin = 0x0040U, .mode = HW_GPIO_MODE_INTERRUPT_RISING, .pinNameStr = "PB6" },

#define HW_GPIO_CUBEMX_PINS_PORT_C \
    { \
        .Pin  = GPIO_PIN_13, \
        .Mode = GPIO_MODE_IT_RISING, \
        .Pull = GPIO_NOPULL, \
    }, \
    { \
        .Pin  = (GPIO_PIN_14|GPIO_PIN_15), \
        .Mode = GPIO_MODE_INPUT, \
        .Pull = GPIO_NOPULL, \
    }, \
    { \
        .Pin   = GPIO_PIN_4, \
        .Mode  = GPIO_MODE_OUTPUT_PP, \
        .Pull  = GPIO_NOPULL, \
        .Speed = GPIO_SPEED_FREQ_LOW, \
    },

#define HW_GPIO_CUBEMX_SIM_PINS_PORT_C \
    { .pin = 0x2000U, .mode = HW_GPIO_MODE_INTERRUPT_RISING, .pinNameStr = "PC13" }, \
    { .pin = 0xC000U, .mode = HW_GPIO_MODE_INPUT,            .pinNameStr = "PC14+PC15" }, \
    { .pin = 0x0010U, .mode = HW_GPIO_MODE_OUTPUT,           .pinNameStr = "PC4" },

#define HW_GPIO_CUBEMX_PINS_PORT_E \
    { \
        .Pin   = GPIO_PIN_7, \
        .Mode  = GPIO_MODE_OUTPUT_PP, \
        .Pull  = GPIO_NOPULL, \
        .Speed = GPIO_SPEED_FREQ_LOW, \
    }, \
    { \
        .Pin  = GPIO_PIN_14, \
        .Mode = GPIO_MODE_INPUT, \
        .Pull = GPIO_NOPULL, \
    },

#define HW_GPIO_CUBEMX_SIM_PINS_PORT_E \
    { .pin = 0x0080U, .mode = HW_GPIO_MODE_OUTPUT, .pinNameStr = "PE7" }, \
    { .pin = 0x4000U, .mode = HW_GPIO_MODE_INPUT,  .pinNameStr = "PE14" },

#endif // HW_GPIO_CHANNELS_CUBEMX_H
