/* Includes */

#include "lib_types.h"
#include "lib_utils.h"
#include "lib_build.h"

#include "HW_GPIO.h"

// Auto-generated CubeMX-derived field values. Re-generated by
// tools/cubemx_to_channels.py (called from
// tools/convert_cubemx_to_canonical.sh) whenever the .ioc changes.
#include "HW_GPIO_channels.cubemx.h"

/* Defines */

/* Typedefs */

/* Private Data Definitions */

#if (BUILD_TARGET == BUILD_TARGET_STM32G4)

static const GPIO_InitTypeDef HW_GPIO_portBPinConfigs[] = { HW_GPIO_CUBEMX_PINS_PORT_B };
static const GPIO_InitTypeDef HW_GPIO_portCPinConfigs[] = { HW_GPIO_CUBEMX_PINS_PORT_C };

const HW_GPIO_config_S HW_GPIO_config =
{
    .ports =
    {
        [HW_GPIO_PORT_B] =
        {
            .pins    = HW_GPIO_portBPinConfigs,
            .numPins = COUNTOF(HW_GPIO_portBPinConfigs),
        },
        [HW_GPIO_PORT_C] =
        {
            .pins    = HW_GPIO_portCPinConfigs,
            .numPins = COUNTOF(HW_GPIO_portCPinConfigs),
        },
    },
};

#elif (BUILD_TARGET == BUILD_TARGET_SIM)

static const HW_GPIO_pinConfig_S HW_GPIO_portBPinConfigs[] = { HW_GPIO_CUBEMX_SIM_PINS_PORT_B };
static const HW_GPIO_pinConfig_S HW_GPIO_portCPinConfigs[] = { HW_GPIO_CUBEMX_SIM_PINS_PORT_C };

const HW_GPIO_config_S HW_GPIO_config =
{
    .ports =
    {
        [HW_GPIO_PORT_B] =
        {
            .pins    = HW_GPIO_portBPinConfigs,
            .numPins = COUNTOF(HW_GPIO_portBPinConfigs),
        },
        [HW_GPIO_PORT_C] =
        {
            .pins    = HW_GPIO_portCPinConfigs,
            .numPins = COUNTOF(HW_GPIO_portCPinConfigs),
        },
    },
};

#else
#error "ERROR! HW_GPIO_config not defined for build target!"
#endif

/* Private Function Definitions */

/* Public Function Definitions */
