#!/usr/bin/env python3
"""Generate `HW_<Module>_channels.cubemx.h` files from CubeMX-generated
main.c, holding macros for the CubeMX-derived field values that the
hand-written `HW_<Module>_channels.c` references.

Reads:  sw/fw/stm32cube/g4/Core/Src/main.c
Writes: sw/fw/src/hw/GPIO/HW_GPIO_channels.cubemx.h
        sw/fw/src/hw/ADC/HW_ADC_channels.cubemx.h

Each generated header defines macros like:
    HW_GPIO_CUBEMX_PINS_PORT_C       # used inside `static const GPIO_InitTypeDef[] = { ... }`
    HW_ADC_CUBEMX_HADC_INIT_ADC1     # used inside `.hadc = { .Init = { ... } }`
    HW_ADC_CUBEMX_INPUTS_ADC1        # used inside `.inputs = { ... }`
    ...

Sim mirrors are emitted alongside the stm32g4 macros so the SIM branch
of channels.c can use them without divergent maintenance.

Called from tools/convert_cubemx_to_canonical.sh. Stdlib only.
"""

import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CUBEMX_MAIN = REPO_ROOT / "sw/fw/stm32cube/g4/Core/Src/main.c"
GPIO_OUT = REPO_ROOT / "sw/fw/src/hw/GPIO/HW_GPIO_channels.cubemx.h"
ADC_OUT = REPO_ROOT / "sw/fw/src/hw/ADC/HW_ADC_channels.cubemx.h"


# ---------------------------------------------------------------------------
# Common helpers
# ---------------------------------------------------------------------------

def extract_function_body(source: str, name: str) -> str | None:
    """Return the `{...}` body of `[static] void <name>(void) { ... }`."""
    pattern = re.compile(
        rf'\b(?:static\s+)?void\s+{re.escape(name)}\s*\(\s*void\s*\)\s*\{{'
    )
    m = pattern.search(source)
    if not m:
        return None
    start = m.end()
    depth = 1
    i = start
    while i < len(source):
        c = source[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return source[start:i]
        i += 1
    return None


def emit_macro(name: str, body_lines: list[str]) -> str:
    """Format a multi-line `#define` from body lines (without trailing `\\`)."""
    if not body_lines:
        return f"#define {name}"
    out = [f"#define {name} \\"]
    for i, line in enumerate(body_lines):
        suffix = " \\" if i < len(body_lines) - 1 else ""
        out.append(line + suffix)
    return "\n".join(out)


def aligned_assignments(items: list[tuple[str, str]], indent: str) -> list[str]:
    """Format `(field, value)` pairs as `.field = value,` lines, with `=`
    aligned to the same column for readability. Matches the project's
    hand-written struct-init style."""
    if not items:
        return []
    width = max(len(f) for f, _ in items)
    return [f"{indent}.{f.ljust(width)} = {v}," for f, v in items]


def file_header(generator_call: str) -> str:
    return (
        f"// AUTO-GENERATED by tools/{generator_call} from\n"
        f"// sw/fw/stm32cube/g4/Core/Src/main.c. Do not hand-edit.\n"
        f"//\n"
        f"// Re-generate via: tools/convert_cubemx_to_canonical.sh\n"
        f"//\n"
        f"// This file holds macros containing CubeMX-derived field values.\n"
        f"// The hand-written HW_*_channels.c references them inside its\n"
        f"// struct initializers; user-managed fields (triggerMode, vref,\n"
        f"// injectedInputs, ...) live there too, outside the macro\n"
        f"// expansions.\n"
    )


# ---------------------------------------------------------------------------
# GPIO
# ---------------------------------------------------------------------------

@dataclass
class GPIOPinConfig:
    pin: str            # e.g. "GPIO_PIN_6" or "GPIO_PIN_15|GPIO_PIN_4"
    mode: str
    pull: str
    speed: str | None
    alternate: str | None


def parse_mx_gpio_init(body: str) -> dict[str, list[GPIOPinConfig]]:
    """Returns: {port_letter: [GPIOPinConfig, ...]}."""
    pins_by_port: dict[str, list[GPIOPinConfig]] = {}
    init_pattern = re.compile(
        r'HAL_GPIO_Init\s*\(\s*GPIO([A-G])\s*,\s*&GPIO_InitStruct\s*\)\s*;'
    )
    prev_end = 0
    for m in init_pattern.finditer(body):
        block = body[prev_end:m.start()]
        fields: dict[str, str] = {}
        for am in re.finditer(r'GPIO_InitStruct\.(\w+)\s*=\s*([^;]+);', block):
            fields[am.group(1)] = am.group(2).strip()
        if "Pin" not in fields:
            # No new Pin set this iteration -- shouldn't happen in well-formed
            # CubeMX output; skip rather than emit a corrupt entry.
            prev_end = m.end()
            continue
        port = m.group(1)
        pins_by_port.setdefault(port, []).append(GPIOPinConfig(
            pin=fields["Pin"],
            mode=fields.get("Mode", ""),
            pull=fields.get("Pull", ""),
            speed=fields.get("Speed"),
            alternate=fields.get("Alternate"),
        ))
        prev_end = m.end()
    return pins_by_port


def normalize_pin_expr(expr: str) -> str:
    """Wrap or-ed pin expressions in parens for safety inside struct context."""
    if "|" in expr or "+" in expr:
        return f"({expr})"
    return expr


def pin_name_str(port: str, pin_expr: str) -> str:
    """`GPIO_PIN_15|GPIO_PIN_4` on port C -> `PC15+PC4`."""
    nums = re.findall(r'GPIO_PIN_(\d+)', pin_expr)
    return "+".join(f"P{port}{n}" for n in nums)


def pin_mask_hex(pin_expr: str) -> str:
    """`GPIO_PIN_15|GPIO_PIN_4` -> `0x8010U` (OR of each line's bit)."""
    nums = re.findall(r'GPIO_PIN_(\d+)', pin_expr)
    mask = 0
    for n in nums:
        mask |= (1 << int(n))
    return f"0x{mask:04X}U"


def sim_mode_enum(hal_mode: str) -> str:
    """Map a HAL GPIO_MODE_* constant to the target-independent
    HW_GPIO_MODE_* enum used by the SIM config."""
    if hal_mode.startswith("GPIO_MODE_IT_"):
        return "HW_GPIO_MODE_INTERRUPT"
    if hal_mode in ("GPIO_MODE_OUTPUT_PP", "GPIO_MODE_OUTPUT_OD"):
        return "HW_GPIO_MODE_OUTPUT"
    # GPIO_MODE_INPUT (and anything else) maps to input.
    return "HW_GPIO_MODE_INPUT"


def gen_gpio_macros(pins_by_port: dict[str, list[GPIOPinConfig]]) -> str:
    parts: list[str] = []
    for port in sorted(pins_by_port):
        pins = pins_by_port[port]

        # --- stm32g4: real GPIO_InitTypeDef entries ---
        body: list[str] = []
        for p in pins:
            entries = [
                ("Pin", normalize_pin_expr(p.pin)),
                ("Mode", p.mode),
                ("Pull", p.pull),
            ]
            if p.speed is not None:
                entries.append(("Speed", p.speed))
            if p.alternate is not None:
                entries.append(("Alternate", p.alternate))
            body.append("    {")
            body.extend(aligned_assignments(entries, indent="        "))
            body.append("    },")
        parts.append(emit_macro(f"HW_GPIO_CUBEMX_PINS_PORT_{port}", body))
        parts.append("")

        # --- sim mirror: pin mask, mode enum, and human-readable name ---
        sim_entries: list[tuple[str, str, str]] = []
        for p in pins:
            sim_entries.append((
                pin_mask_hex(p.pin),
                sim_mode_enum(p.mode),
                pin_name_str(port, p.pin),
            ))
        # Align the mode column so the trailing name strings line up.
        mode_width = max((len(m) for _, m, _ in sim_entries), default=0)
        sim_body: list[str] = []
        for mask, mode, name in sim_entries:
            sim_body.append(
                f'    {{ .pin = {mask}, .mode = {(mode + ",").ljust(mode_width + 1)} '
                f'.pinNameStr = "{name}" }},'
            )
        parts.append(emit_macro(
            f"HW_GPIO_CUBEMX_SIM_PINS_PORT_{port}", sim_body))
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_gpio_header(pins_by_port: dict[str, list[GPIOPinConfig]]) -> None:
    macros = gen_gpio_macros(pins_by_port)
    content = (
        f"{file_header('cubemx_to_channels.py')}"
        f"\n"
        f"#ifndef HW_GPIO_CHANNELS_CUBEMX_H\n"
        f"#define HW_GPIO_CHANNELS_CUBEMX_H\n"
        f"\n"
        f"{macros}\n"
        f"#endif // HW_GPIO_CHANNELS_CUBEMX_H\n"
    )
    GPIO_OUT.write_text(content, encoding="utf-8")
    print(f"  wrote {GPIO_OUT.relative_to(REPO_ROOT)} "
          f"({sum(len(v) for v in pins_by_port.values())} pins, "
          f"{len(pins_by_port)} ports)")


# ---------------------------------------------------------------------------
# ADC
# ---------------------------------------------------------------------------

@dataclass
class ADCConfig:
    instance: str                      # e.g. "ADC1"
    init: list[tuple[str, str]]        # [(field, value), ...]
    multimode: list[tuple[str, str]] | None
    inputs: list[dict[str, str]]       # list of sConfig field dicts


def parse_mx_adc_init(body: str, hadc_var: str) -> ADCConfig | None:
    """Parse one `MX_ADC*_Init` body. `hadc_var` is the local handle name
    CubeMX uses, e.g. `hadc1` for ADC1."""
    instance_match = re.search(
        rf'\b{re.escape(hadc_var)}\.Instance\s*=\s*(ADC\d+)\s*;', body)
    if not instance_match:
        return None
    instance = instance_match.group(1)

    # hadcN.Init.X = Y;  -- preserve declaration order
    init_pairs: list[tuple[str, str]] = []
    for m in re.finditer(
            rf'\b{re.escape(hadc_var)}\.Init\.(\w+)\s*=\s*([^;]+);', body):
        init_pairs.append((m.group(1), m.group(2).strip()))

    # multimode: only present when MultiModeConfigChannel is called.
    multimode: list[tuple[str, str]] | None = None
    if re.search(r'\bHAL_ADCEx_MultiModeConfigChannel\s*\(', body):
        multimode = []
        for m in re.finditer(r'\bmultimode\.(\w+)\s*=\s*([^;]+);', body):
            multimode.append((m.group(1), m.group(2).strip()))

    # Each HAL_ADC_ConfigChannel call corresponds to one input. Collect
    # the sConfig.X assignments preceding each call (since the previous
    # one).
    inputs: list[dict[str, str]] = []
    cc_pattern = re.compile(r'\bHAL_ADC_ConfigChannel\s*\(')
    prev_end = 0
    for m in cc_pattern.finditer(body):
        block = body[prev_end:m.start()]
        fields: dict[str, str] = {}
        for am in re.finditer(r'\bsConfig\.(\w+)\s*=\s*([^;]+);', block):
            fields[am.group(1)] = am.group(2).strip()
        if fields:
            inputs.append(fields)
        prev_end = m.end()

    return ADCConfig(
        instance=instance, init=init_pairs,
        multimode=multimode, inputs=inputs,
    )


def channel_index_from_constant(channel: str) -> int | None:
    """`ADC_CHANNEL_6` -> 6. Returns None for non-numeric channels
    (e.g. ADC_CHANNEL_TEMPSENSOR), which the sparse `inputs[N]` array
    can't index by physical IN# anyway."""
    m = re.match(r'ADC_CHANNEL_(\d+)\b', channel)
    return int(m.group(1)) if m else None


def gen_adc_macros(adcs: list[ADCConfig]) -> str:
    parts: list[str] = []
    for adc in adcs:
        name = adc.instance
        parts.append(f"// ----- {name} -----")
        parts.append("")

        # Instance constant.
        parts.append(f"#define HW_ADC_CUBEMX_HADC_INSTANCE_{name}  {name}")
        parts.append("")

        # hadc.Init fields.
        if adc.init:
            init_lines = aligned_assignments(adc.init, indent="    ")
            parts.append(emit_macro(f"HW_ADC_CUBEMX_HADC_INIT_{name}",
                                    init_lines))
            parts.append("")

        # multimode (if present).
        if adc.multimode is not None and adc.multimode:
            mm_lines = aligned_assignments(adc.multimode, indent="    ")
            parts.append(emit_macro(f"HW_ADC_CUBEMX_MULTIMODE_{name}",
                                    mm_lines))
            parts.append("")

        # Regular-sequence inputs.
        if adc.inputs:
            input_lines: list[str] = []
            for inp in adc.inputs:
                ch = inp.get("Channel", "")
                idx = channel_index_from_constant(ch)
                if idx is None:
                    print(f"  WARN: skipping non-numeric channel {ch!r} "
                          f"on {name} (internal channels not yet "
                          f"supported)", file=sys.stderr)
                    continue
                # Sub-struct field assignments, aligned.
                sc_pairs = list(inp.items())
                sc_lines = aligned_assignments(sc_pairs,
                                               indent="            ")
                input_lines.append(f"    [{idx}] =")
                input_lines.append("    {")
                input_lines.append("        .enabled = true,")
                input_lines.append("        .sConfig =")
                input_lines.append("        {")
                input_lines.extend(sc_lines)
                input_lines.append("        },")
                input_lines.append("    },")
            parts.append(emit_macro(f"HW_ADC_CUBEMX_INPUTS_{name}",
                                    input_lines))
            parts.append("")

            # sim mirror: same enabled-input set, just with a name string.
            sim_lines: list[str] = []
            for inp in adc.inputs:
                ch = inp.get("Channel", "")
                idx = channel_index_from_constant(ch)
                if idx is None:
                    continue
                sim_lines.append(
                    f'    [{idx}] = {{ .enabled = true, '
                    f'.inputNameStr = "{name}_IN{idx}" }},'
                )
            parts.append(emit_macro(f"HW_ADC_CUBEMX_SIM_INPUTS_{name}",
                                    sim_lines))
            parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_adc_header(adcs: list[ADCConfig]) -> None:
    macros = gen_adc_macros(adcs)
    content = (
        f"{file_header('cubemx_to_channels.py')}"
        f"\n"
        f"#ifndef HW_ADC_CHANNELS_CUBEMX_H\n"
        f"#define HW_ADC_CHANNELS_CUBEMX_H\n"
        f"\n"
        f"{macros}\n"
        f"#endif // HW_ADC_CHANNELS_CUBEMX_H\n"
    )
    ADC_OUT.write_text(content, encoding="utf-8")
    total_inputs = sum(len(a.inputs) for a in adcs)
    print(f"  wrote {ADC_OUT.relative_to(REPO_ROOT)} "
          f"({len(adcs)} ADCs, {total_inputs} inputs)")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main() -> int:
    if not CUBEMX_MAIN.is_file():
        print(f"Error: {CUBEMX_MAIN} not found.", file=sys.stderr)
        return 1
    source = CUBEMX_MAIN.read_text(encoding="utf-8", errors="replace")

    # GPIO ------------------------------------------------------------
    gpio_body = extract_function_body(source, "MX_GPIO_Init")
    if gpio_body is None:
        print("  WARN: MX_GPIO_Init not found in cubemx main.c; "
              "skipping GPIO header.", file=sys.stderr)
    else:
        pins_by_port = parse_mx_gpio_init(gpio_body)
        if not pins_by_port:
            print("  WARN: no HAL_GPIO_Init calls parsed; "
                  "writing empty GPIO header.", file=sys.stderr)
        write_gpio_header(pins_by_port)

    # ADC -------------------------------------------------------------
    # Find every MX_ADCN_Init function (typically MX_ADC1_Init,
    # MX_ADC2_Init, ...) and parse each. Both the prototype and the
    # definition match `void NAME(void)`, so dedupe by name.
    adc_funcs_raw = re.findall(
        r'\bvoid\s+(MX_ADC(\d+)_Init)\s*\(\s*void\s*\)', source)
    adc_funcs = sorted(set(adc_funcs_raw), key=lambda x: int(x[1]))
    adcs: list[ADCConfig] = []
    for func_name, n in adc_funcs:
        body = extract_function_body(source, func_name)
        if body is None:
            continue
        cfg = parse_mx_adc_init(body, hadc_var=f"hadc{n}")
        if cfg is None:
            print(f"  WARN: couldn't parse {func_name}; skipping.",
                  file=sys.stderr)
            continue
        adcs.append(cfg)
    if not adcs:
        print("  WARN: no MX_ADC*_Init functions found; "
              "writing empty ADC header.", file=sys.stderr)
    write_adc_header(adcs)

    return 0


if __name__ == "__main__":
    sys.exit(main())
