#!/usr/bin/env python3
"""Generate `HW_<Module>_channels.cubemx.h` files from CubeMX-generated
main.c, holding macros for the CubeMX-derived field values that the
hand-written `HW_<Module>_channels.c` references.

Reads:  sw/fw/stm32cube/g4/Core/Src/main.c
Writes: sw/fw/src/hw/GPIO/HW_GPIO_channels.cubemx.h
        sw/fw/src/hw/ADC/HW_ADC_channels.cubemx.h

Each generated header defines macros like:
    HW_GPIO_CUBEMX_PINS_PORT_C       # used inside `static const GPIO_InitTypeDef[] = { ... }`
    HW_ADC_CUBEMX_HADC_INIT_ADC1     # used inside `.hadc = { .Init = { ... } }`
    HW_ADC_CUBEMX_INPUTS_ADC1        # used inside `.inputs = { ... }`
    ...

Sim mirrors are emitted alongside the stm32g4 macros so the SIM branch
of channels.c can use them without divergent maintenance.

Called from tools/convert_cubemx_to_canonical.sh. Stdlib only.
"""

import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CUBEMX_MAIN = REPO_ROOT / "sw/fw/stm32cube/g4/Core/Src/main.c"
CUBEMX_MSP = REPO_ROOT / "sw/fw/stm32cube/g4/Core/Src/stm32g4xx_hal_msp.c"
GPIO_OUT = REPO_ROOT / "sw/fw/src/hw/GPIO/HW_GPIO_channels.cubemx.h"
ADC_OUT = REPO_ROOT / "sw/fw/src/hw/ADC/HW_ADC_channels.cubemx.h"
SPI_OUT = REPO_ROOT / "sw/fw/src/hw/SPI/HW_SPI_channels.cubemx.h"
TIM_OUT = REPO_ROOT / "sw/fw/src/hw/TIM/HW_TIM_channels.cubemx.h"

# STM32G4 timers with a 32-bit counter; the rest are 16-bit. Used to fill
# the SIM config's counterWidthBits (the stm32g4 side never needs it).
TIM_32BIT_INSTANCES = {2, 5}

# Timer kernel clock the SIM config's countsPerUs is derived against: HSE
# 24 MHz (HSE_VALUE in sw/fw/src/hw/stm32g4/stm32g4xx_hal_conf.h) / PLLM 2
# x PLLN 24 / PLLR 2 = 144 MHz, with both APB prescalers at 1 so the timer
# clock equals HCLK. Update alongside SystemClock_Config.
TIM_KERNEL_CLOCK_HZ = 144_000_000

# countsPerUs values that do not follow from the prescaler. A timer whose
# prescaled rate is not a whole number of counts per microsecond needs one
# here -- a deliberate choice by the owner of the sim timebase, recorded
# rather than silently rounded.
TIM_COUNTS_PER_US_OVERRIDE: dict[int, int] = {}


# ---------------------------------------------------------------------------
# Common helpers
# ---------------------------------------------------------------------------

def extract_function_body(source: str, name: str) -> str | None:
    """Return the `{...}` body of `[static] void <name>(void) { ... }`."""
    pattern = re.compile(
        rf'\b(?:static\s+)?void\s+{re.escape(name)}\s*\(\s*void\s*\)\s*\{{'
    )
    m = pattern.search(source)
    if not m:
        return None
    start = m.end()
    depth = 1
    i = start
    while i < len(source):
        c = source[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return source[start:i]
        i += 1
    return None


def emit_macro(name: str, body_lines: list[str]) -> str:
    """Format a multi-line `#define` from body lines (without trailing `\\`)."""
    if not body_lines:
        return f"#define {name}"
    out = [f"#define {name} \\"]
    for i, line in enumerate(body_lines):
        suffix = " \\" if i < len(body_lines) - 1 else ""
        out.append(line + suffix)
    return "\n".join(out)


def aligned_assignments(items: list[tuple[str, str]], indent: str) -> list[str]:
    """Format `(field, value)` pairs as `.field = value,` lines, with `=`
    aligned to the same column for readability. Matches the project's
    hand-written struct-init style."""
    if not items:
        return []
    width = max(len(f) for f, _ in items)
    return [f"{indent}.{f.ljust(width)} = {v}," for f, v in items]


def file_header(generator_call: str) -> str:
    return (
        f"// AUTO-GENERATED by tools/{generator_call} from\n"
        f"// sw/fw/stm32cube/g4/Core/Src/main.c. Do not hand-edit.\n"
        f"//\n"
        f"// Re-generate via: tools/convert_cubemx_to_canonical.sh\n"
        f"//\n"
        f"// This file holds macros containing CubeMX-derived field values.\n"
        f"// The hand-written HW_*_channels.c references them inside its\n"
        f"// struct initializers; user-managed fields (triggerMode, vref,\n"
        f"// injectedInputs, ...) live there too, outside the macro\n"
        f"// expansions.\n"
    )


# ---------------------------------------------------------------------------
# GPIO
# ---------------------------------------------------------------------------

@dataclass
class GPIOPinConfig:
    pin: str            # e.g. "GPIO_PIN_6" or "GPIO_PIN_15|GPIO_PIN_4"
    mode: str
    pull: str
    speed: str | None
    alternate: str | None


def parse_mx_gpio_init(body: str) -> dict[str, list[GPIOPinConfig]]:
    """Returns: {port_letter: [GPIOPinConfig, ...]}."""
    pins_by_port: dict[str, list[GPIOPinConfig]] = {}
    init_pattern = re.compile(
        r'HAL_GPIO_Init\s*\(\s*GPIO([A-G])\s*,\s*&GPIO_InitStruct\s*\)\s*;'
    )
    prev_end = 0
    for m in init_pattern.finditer(body):
        block = body[prev_end:m.start()]
        fields: dict[str, str] = {}
        for am in re.finditer(r'GPIO_InitStruct\.(\w+)\s*=\s*([^;]+);', block):
            fields[am.group(1)] = am.group(2).strip()
        if "Pin" not in fields:
            # No new Pin set this iteration -- shouldn't happen in well-formed
            # CubeMX output; skip rather than emit a corrupt entry.
            prev_end = m.end()
            continue
        port = m.group(1)
        pins_by_port.setdefault(port, []).append(GPIOPinConfig(
            pin=fields["Pin"],
            mode=fields.get("Mode", ""),
            pull=fields.get("Pull", ""),
            speed=fields.get("Speed"),
            alternate=fields.get("Alternate"),
        ))
        prev_end = m.end()
    return pins_by_port


def normalize_pin_expr(expr: str) -> str:
    """Wrap or-ed pin expressions in parens for safety inside struct context."""
    if "|" in expr or "+" in expr:
        return f"({expr})"
    return expr


def pin_name_str(port: str, pin_expr: str) -> str:
    """`GPIO_PIN_15|GPIO_PIN_4` on port C -> `PC15+PC4`."""
    nums = re.findall(r'GPIO_PIN_(\d+)', pin_expr)
    return "+".join(f"P{port}{n}" for n in nums)


def pin_mask_hex(pin_expr: str) -> str:
    """`GPIO_PIN_15|GPIO_PIN_4` -> `0x8010U` (OR of each line's bit)."""
    nums = re.findall(r'GPIO_PIN_(\d+)', pin_expr)
    mask = 0
    for n in nums:
        mask |= (1 << int(n))
    return f"0x{mask:04X}U"


def sim_mode_enum(hal_mode: str) -> str:
    """Map a HAL GPIO_MODE_* constant to the target-independent
    HW_GPIO_MODE_* enum used by the SIM config."""
    if hal_mode.startswith("GPIO_MODE_IT_"):
        return "HW_GPIO_MODE_INTERRUPT"
    if hal_mode in ("GPIO_MODE_OUTPUT_PP", "GPIO_MODE_OUTPUT_OD"):
        return "HW_GPIO_MODE_OUTPUT"
    # GPIO_MODE_INPUT (and anything else) maps to input.
    return "HW_GPIO_MODE_INPUT"


def gen_gpio_macros(pins_by_port: dict[str, list[GPIOPinConfig]]) -> str:
    parts: list[str] = []
    for port in sorted(pins_by_port):
        pins = pins_by_port[port]

        # --- stm32g4: real GPIO_InitTypeDef entries ---
        body: list[str] = []
        for p in pins:
            entries = [
                ("Pin", normalize_pin_expr(p.pin)),
                ("Mode", p.mode),
                ("Pull", p.pull),
            ]
            if p.speed is not None:
                entries.append(("Speed", p.speed))
            if p.alternate is not None:
                entries.append(("Alternate", p.alternate))
            body.append("    {")
            body.extend(aligned_assignments(entries, indent="        "))
            body.append("    },")
        parts.append(emit_macro(f"HW_GPIO_CUBEMX_PINS_PORT_{port}", body))
        parts.append("")

        # --- sim mirror: pin mask, mode enum, and human-readable name ---
        sim_entries: list[tuple[str, str, str]] = []
        for p in pins:
            sim_entries.append((
                pin_mask_hex(p.pin),
                sim_mode_enum(p.mode),
                pin_name_str(port, p.pin),
            ))
        # Align the mode column so the trailing name strings line up.
        mode_width = max((len(m) for _, m, _ in sim_entries), default=0)
        sim_body: list[str] = []
        for mask, mode, name in sim_entries:
            sim_body.append(
                f'    {{ .pin = {mask}, .mode = {(mode + ",").ljust(mode_width + 1)} '
                f'.pinNameStr = "{name}" }},'
            )
        parts.append(emit_macro(
            f"HW_GPIO_CUBEMX_SIM_PINS_PORT_{port}", sim_body))
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_gpio_header(pins_by_port: dict[str, list[GPIOPinConfig]]) -> None:
    macros = gen_gpio_macros(pins_by_port)
    content = (
        f"{file_header('cubemx_to_channels.py')}"
        f"\n"
        f"#ifndef HW_GPIO_CHANNELS_CUBEMX_H\n"
        f"#define HW_GPIO_CHANNELS_CUBEMX_H\n"
        f"\n"
        f"{macros}\n"
        f"#endif // HW_GPIO_CHANNELS_CUBEMX_H\n"
    )
    GPIO_OUT.write_text(content, encoding="utf-8")
    print(f"  wrote {GPIO_OUT.relative_to(REPO_ROOT)} "
          f"({sum(len(v) for v in pins_by_port.values())} pins, "
          f"{len(pins_by_port)} ports)")


# ---------------------------------------------------------------------------
# ADC
# ---------------------------------------------------------------------------

@dataclass
class ADCConfig:
    instance: str                      # e.g. "ADC1"
    init: list[tuple[str, str]]        # [(field, value), ...]
    multimode: list[tuple[str, str]] | None
    inputs: list[dict[str, str]]       # list of sConfig field dicts


def parse_mx_adc_init(body: str, hadc_var: str) -> ADCConfig | None:
    """Parse one `MX_ADC*_Init` body. `hadc_var` is the local handle name
    CubeMX uses, e.g. `hadc1` for ADC1."""
    instance_match = re.search(
        rf'\b{re.escape(hadc_var)}\.Instance\s*=\s*(ADC\d+)\s*;', body)
    if not instance_match:
        return None
    instance = instance_match.group(1)

    # hadcN.Init.X = Y;  -- preserve declaration order
    init_pairs: list[tuple[str, str]] = []
    for m in re.finditer(
            rf'\b{re.escape(hadc_var)}\.Init\.(\w+)\s*=\s*([^;]+);', body):
        init_pairs.append((m.group(1), m.group(2).strip()))

    # multimode: only present when MultiModeConfigChannel is called.
    multimode: list[tuple[str, str]] | None = None
    if re.search(r'\bHAL_ADCEx_MultiModeConfigChannel\s*\(', body):
        multimode = []
        for m in re.finditer(r'\bmultimode\.(\w+)\s*=\s*([^;]+);', body):
            multimode.append((m.group(1), m.group(2).strip()))

    # Each HAL_ADC_ConfigChannel call corresponds to one input. CubeMX sets
    # the common sConfig fields (SamplingTime, SingleDiff, ...) once and then
    # mutates only Channel/Rank before each subsequent call, relying on the
    # struct persisting its other fields. Our per-input storage is independent,
    # so snapshot the running sConfig at each call to give every input its full
    # field set (same walk the TIM/injected parsers use).
    inputs: list[dict[str, str]] = []
    running: dict[str, str] = {}
    token = re.compile(
        r'\bsConfig\.(\w+)\s*=\s*([^;]+);'
        r'|\bHAL_ADC_ConfigChannel\s*\(')
    for m in token.finditer(body):
        if m.group(1) is not None:
            running[m.group(1)] = m.group(2).strip()
        else:
            inputs.append(dict(running))

    return ADCConfig(
        instance=instance, init=init_pairs,
        multimode=multimode, inputs=inputs,
    )


def channel_index_from_constant(channel: str) -> int | None:
    """`ADC_CHANNEL_6` -> 6. Returns None for non-numeric channels
    (e.g. ADC_CHANNEL_TEMPSENSOR), which the sparse `inputs[N]` array
    can't index by physical IN# anyway."""
    m = re.match(r'ADC_CHANNEL_(\d+)\b', channel)
    return int(m.group(1)) if m else None


def gen_adc_macros(adcs: list[ADCConfig]) -> str:
    parts: list[str] = []
    for adc in adcs:
        name = adc.instance
        parts.append(f"// ----- {name} -----")
        parts.append("")

        # Instance constant.
        parts.append(f"#define HW_ADC_CUBEMX_HADC_INSTANCE_{name}  {name}")
        parts.append("")

        # hadc.Init fields.
        if adc.init:
            init_lines = aligned_assignments(adc.init, indent="    ")
            parts.append(emit_macro(f"HW_ADC_CUBEMX_HADC_INIT_{name}",
                                    init_lines))
            parts.append("")

        # multimode (if present).
        if adc.multimode is not None and adc.multimode:
            mm_lines = aligned_assignments(adc.multimode, indent="    ")
            parts.append(emit_macro(f"HW_ADC_CUBEMX_MULTIMODE_{name}",
                                    mm_lines))
            parts.append("")

        # Regular-sequence inputs.
        if adc.inputs:
            input_lines: list[str] = []
            for inp in adc.inputs:
                ch = inp.get("Channel", "")
                idx = channel_index_from_constant(ch)
                if idx is None:
                    print(f"  WARN: skipping non-numeric channel {ch!r} "
                          f"on {name} (internal channels not yet "
                          f"supported)", file=sys.stderr)
                    continue
                # Sub-struct field assignments, aligned.
                sc_pairs = list(inp.items())
                sc_lines = aligned_assignments(sc_pairs,
                                               indent="            ")
                input_lines.append(f"    [{idx}] =")
                input_lines.append("    {")
                input_lines.append("        .enabled = true,")
                input_lines.append("        .sConfig =")
                input_lines.append("        {")
                input_lines.extend(sc_lines)
                input_lines.append("        },")
                input_lines.append("    },")
            parts.append(emit_macro(f"HW_ADC_CUBEMX_INPUTS_{name}",
                                    input_lines))
            parts.append("")

            # sim mirror: same enabled-input set, just with a name string.
            sim_lines: list[str] = []
            for inp in adc.inputs:
                ch = inp.get("Channel", "")
                idx = channel_index_from_constant(ch)
                if idx is None:
                    continue
                sim_lines.append(
                    f'    [{idx}] = {{ .enabled = true, '
                    f'.inputNameStr = "{name}_IN{idx}" }},'
                )
            parts.append(emit_macro(f"HW_ADC_CUBEMX_SIM_INPUTS_{name}",
                                    sim_lines))
            parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_adc_header(adcs: list[ADCConfig]) -> None:
    macros = gen_adc_macros(adcs)
    content = (
        f"{file_header('cubemx_to_channels.py')}"
        f"\n"
        f"#ifndef HW_ADC_CHANNELS_CUBEMX_H\n"
        f"#define HW_ADC_CHANNELS_CUBEMX_H\n"
        f"\n"
        f"{macros}\n"
        f"#endif // HW_ADC_CHANNELS_CUBEMX_H\n"
    )
    ADC_OUT.write_text(content, encoding="utf-8")
    total_inputs = sum(len(a.inputs) for a in adcs)
    print(f"  wrote {ADC_OUT.relative_to(REPO_ROOT)} "
          f"({len(adcs)} ADCs, {total_inputs} inputs)")


# ---------------------------------------------------------------------------
# SPI
# ---------------------------------------------------------------------------

@dataclass
class SPIConfig:
    instance: str                      # e.g. "SPI1"
    init: list[tuple[str, str]]        # [(field, value), ...] from hspiN.Init.*


def parse_mx_spi_init(body: str, hspi_var: str) -> SPIConfig | None:
    """Parse one `MX_SPI*_Init` body. `hspi_var` is CubeMX's handle name,
    e.g. `hspi1` for SPI1."""
    instance_match = re.search(
        rf'\b{re.escape(hspi_var)}\.Instance\s*=\s*(SPI\d+)\s*;', body)
    if not instance_match:
        return None
    instance = instance_match.group(1)

    # hspiN.Init.X = Y;  -- preserve declaration order so the generated macro
    # reads the same as CubeMX's struct.
    init_pairs: list[tuple[str, str]] = []
    for m in re.finditer(
            rf'\b{re.escape(hspi_var)}\.Init\.(\w+)\s*=\s*([^;]+);', body):
        init_pairs.append((m.group(1), m.group(2).strip()))

    return SPIConfig(instance=instance, init=init_pairs)


def gen_spi_macros(spis: list[SPIConfig]) -> str:
    parts: list[str] = []
    for spi in spis:
        name = spi.instance
        parts.append(f"// ----- {name} -----")
        parts.append("")
        # The whole SPI_InitTypeDef body, used inside `.hspi = { .Init = { ... } }`.
        # No sim mirror: the SIM branch of HW_SPI_channels.c has no hspi.
        if spi.init:
            init_lines = aligned_assignments(spi.init, indent="    ")
            parts.append(emit_macro(f"HW_SPI_CUBEMX_INIT_{name}", init_lines))
            parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def write_spi_header(spis: list[SPIConfig]) -> None:
    macros = gen_spi_macros(spis)
    content = (
        f"{file_header('cubemx_to_channels.py')}"
        f"\n"
        f"#ifndef HW_SPI_CHANNELS_CUBEMX_H\n"
        f"#define HW_SPI_CHANNELS_CUBEMX_H\n"
        f"\n"
        f"{macros}\n"
        f"#endif // HW_SPI_CHANNELS_CUBEMX_H\n"
    )
    SPI_OUT.write_text(content, encoding="utf-8")
    print(f"  wrote {SPI_OUT.relative_to(REPO_ROOT)} ({len(spis)} SPIs)")


# ---------------------------------------------------------------------------
# TIM
# ---------------------------------------------------------------------------

@dataclass
class TIMOcConfig:
    channel: str                       # e.g. "TIM_CHANNEL_1"
    is_pwm: bool                       # PWM_ConfigChannel vs OC_ConfigChannel
    fields: dict[str, str]             # snapshot of sConfigOC at the call


@dataclass
class TIMConfig:
    instance: str                              # e.g. "TIM1"
    init: list[tuple[str, str]]                # htimN.Init.* pairs
    oc_units: list[TIMOcConfig]                # one per (PWM|OC)_ConfigChannel call
    bdt: list[tuple[str, str]] | None          # break/dead-time block, if configured
    master: list[tuple[str, str]] | None       # master/TRGO block, if configured
    break_inputs: list[tuple[str, dict[str, str]]]  # (break id, sBreakInputConfig) per ConfigBreakInput


def parse_complementary_channels(msp_source: str) -> set[tuple[int, int]]:
    """Find (timer, channel) pairs whose CHxN line is routed to a pin, from
    the `PEx ------> TIMy_CHzN` comments CubeMX leaves in HAL_TIM_MspPostInit.
    These are the complementary outputs."""
    comp: set[tuple[int, int]] = set()
    for m in re.finditer(r'\bTIM(\d+)_CH(\d+)N\b', msp_source):
        comp.add((int(m.group(1)), int(m.group(2))))
    return comp


def parse_mx_tim_init(body: str, htim_var: str) -> TIMConfig | None:
    """Parse one `MX_TIM*_Init` body. `htim_var` is CubeMX's handle name,
    e.g. `htim1` for TIM1."""
    instance_match = re.search(
        rf'\b{re.escape(htim_var)}\.Instance\s*=\s*(TIM\d+)\s*;', body)
    if not instance_match:
        return None
    instance = instance_match.group(1)

    init_pairs: list[tuple[str, str]] = []
    for m in re.finditer(
            rf'\b{re.escape(htim_var)}\.Init\.(\w+)\s*=\s*([^;]+);', body):
        init_pairs.append((m.group(1), m.group(2).strip()))

    # Output-compare units: walk sConfigOC assignments and (PWM|OC)
    # ConfigChannel calls in source order. CubeMX sets the common fields
    # once, then mutates only what differs before each call, so a running
    # snapshot reproduces each channel's effective config.
    oc_units: list[TIMOcConfig] = []
    running: dict[str, str] = {}
    token = re.compile(
        r'sConfigOC\.(\w+)\s*=\s*([^;]+);'
        r'|HAL_TIM_(PWM|OC)_ConfigChannel\s*\(\s*&' + re.escape(htim_var)
        + r'\s*,\s*&sConfigOC\s*,\s*(TIM_CHANNEL_\d+)\s*\)')
    for m in token.finditer(body):
        if m.group(1) is not None:
            running[m.group(1)] = m.group(2).strip()
        else:
            oc_units.append(TIMOcConfig(
                channel=m.group(4), is_pwm=(m.group(3) == "PWM"),
                fields=dict(running)))

    bdt: list[tuple[str, str]] | None = None
    if re.search(r'\bHAL_TIMEx_ConfigBreakDeadTime\s*\(', body):
        bdt = [(m.group(1), m.group(2).strip()) for m in re.finditer(
            r'\bsBreakDeadTimeConfig\.(\w+)\s*=\s*([^;]+);', body)]

    master: list[tuple[str, str]] | None = None
    if re.search(r'\bHAL_TIMEx_MasterConfigSynchronization\s*\(', body):
        master = [(m.group(1), m.group(2).strip()) for m in re.finditer(
            r'\bsMasterConfig\.(\w+)\s*=\s*([^;]+);', body)]

    # Break-input sources (BRK / BRK2): snapshot sBreakInputConfig at each
    # HAL_TIMEx_ConfigBreakInput call (the config struct is reused across
    # calls, mutated only where it differs), same as the OC-channel walk.
    break_inputs: list[tuple[str, dict[str, str]]] = []
    running_bi: dict[str, str] = {}
    bi_token = re.compile(
        r'sBreakInputConfig\.(\w+)\s*=\s*([^;]+);'
        r'|HAL_TIMEx_ConfigBreakInput\s*\(\s*&' + re.escape(htim_var)
        + r'\s*,\s*(TIM_BREAKINPUT_\w+)\s*,\s*&sBreakInputConfig\s*\)')
    for m in bi_token.finditer(body):
        if m.group(1) is not None:
            running_bi[m.group(1)] = m.group(2).strip()
        else:
            break_inputs.append((m.group(3), dict(running_bi)))

    return TIMConfig(instance=instance, init=init_pairs,
                     oc_units=oc_units, bdt=bdt, master=master,
                     break_inputs=break_inputs)


def tim_instance_num(instance: str) -> int:
    return int(re.search(r'(\d+)', instance).group(1))


def tim_channel_num(channel: str) -> int:
    return int(re.search(r'(\d+)', channel).group(1))


def sim_count_dir(counter_mode: str) -> str:
    if counter_mode == "TIM_COUNTERMODE_DOWN":
        return "HW_TIM_COUNT_DOWN"
    if counter_mode.startswith("TIM_COUNTERMODE_CENTERALIGNED"):
        return "HW_TIM_COUNT_CENTER"
    return "HW_TIM_COUNT_UP"


def sim_trgo_source(trgo: str) -> str:
    if trgo.endswith("_UPDATE"):
        return "HW_TIM_TRGO_UPDATE"
    if trgo.endswith("_RESET"):
        return "HW_TIM_TRGO_NONE"
    return "HW_TIM_TRGO_OC_MATCH"      # OC1REF / OC2REF / ... (TRGO or TRGO2)


def sim_trgo_oc_unit(trgo: str) -> int:
    """Dense OC-unit index behind an OCxREF trigger source (OC1REF -> 0)."""
    match = re.search(r'OC(\d)', trgo)
    return int(match.group(1)) - 1 if match else 0


def sim_counts_per_us(inum: int, prescaler: str) -> int | None:
    """Counter counts per sim microsecond, from the timer kernel clock and the
    CubeMX prescaler. Returns None when the rate is not a whole number of
    counts per microsecond and no override covers the timer -- the caller
    leaves countsPerUs out rather than emit a rounded rate the sim timebase
    would silently drift on."""
    if inum in TIM_COUNTS_PER_US_OVERRIDE:
        return TIM_COUNTS_PER_US_OVERRIDE[inum]
    try:
        divider = int(prescaler) + 1
    except ValueError:
        return None
    tick_hz, remainder = divmod(TIM_KERNEL_CLOCK_HZ, divider)
    if remainder != 0 or tick_hz % 1_000_000 != 0:
        return None
    return tick_hz // 1_000_000


def tim_trgo_constant(tim: TIMConfig) -> str:
    """The trigger source the sim's single trigger output models. TRGO2 wins
    when configured: it is the ADC-facing line (injected hardware triggers),
    which is the output a sim consumer wires to."""
    if tim.master is None:
        return "TIM_TRGO_RESET"
    master = dict(tim.master)
    trgo2 = master.get("MasterOutputTrigger2", "TIM_TRGO2_RESET")
    if not trgo2.endswith("_RESET"):
        return trgo2
    return master.get("MasterOutputTrigger", "TIM_TRGO_RESET")


def gen_tim_oc_macros(name: str, tim: TIMConfig,
                      complementary: set[tuple[int, int]]) -> list[str]:
    """One G4 macro per output-compare unit, holding the per-output fields a
    logical channel carries (complementary, HAL channel id, OC init). The
    hand-written channels.c prepends .peripheral / .role / .ocUnit."""
    inum = tim_instance_num(tim.instance)
    parts: list[str] = []
    for oc in tim.oc_units:
        chnum = tim_channel_num(oc.channel)
        is_comp = (inum, chnum) in complementary
        lines: list[str] = [
            f"    .complementary = {'true' if is_comp else 'false'},",
            f"    .channel       = {oc.channel},",
            "    .oc =",
            "    {",
        ]
        lines.extend(aligned_assignments(list(oc.fields.items()),
                                         indent="        "))
        lines.append("    },")
        parts.append(emit_macro(f"HW_TIM_CUBEMX_G4_OC_{name}_CH{chnum}", lines))
        parts.append("")
    return parts


def gen_tim_sim_oc_macros(name: str, tim: TIMConfig,
                          complementary: set[tuple[int, int]]) -> list[str]:
    """One SIM macro per output-compare unit, mirroring the per-output fields."""
    inum = tim_instance_num(tim.instance)
    parts: list[str] = []
    for oc in tim.oc_units:
        chnum = tim_channel_num(oc.channel)
        is_comp = (inum, chnum) in complementary
        pulse = oc.fields.get("Pulse", "0")
        idle = oc.fields.get("OCIdleState", "TIM_OCIDLESTATE_RESET")
        inactive = "1U" if idle.endswith("_SET") else "0U"
        line = (f"    .complementary = {'true' if is_comp else 'false'}, "
                f".compare = {pulse}U, .inactiveLevel = {inactive},")
        parts.append(emit_macro(f"HW_TIM_CUBEMX_SIM_OC_{name}_CH{chnum}", [line]))
        parts.append("")
    return parts


def gen_tim_break_input_macro(name: str, tim: TIMConfig) -> str:
    lines: list[str] = []
    for idx, (break_id, fields) in enumerate(tim.break_inputs):
        lines.append(f"    [{idx}] =")
        lines.append("    {")
        lines.append("        .enabled    = true,")
        lines.append(f"        .breakInput = {break_id},")
        lines.append("        .config =")
        lines.append("        {")
        lines.extend(aligned_assignments(list(fields.items()),
                                         indent="            "))
        lines.append("        },")
        lines.append("    },")
    return emit_macro(f"HW_TIM_CUBEMX_BRKIN_{name}", lines)


def gen_tim_peripheral_macro(name: str, tim: TIMConfig,
                             has_bdt: bool, has_brkin: bool, has_trgo: bool) -> str:
    body: list[str] = [
        "    .htim =",
        "    {",
        f"        .Instance = {tim.instance},",
        f"        .Init = {{ HW_TIM_CUBEMX_INIT_{name} }},",
        "    },",
    ]
    body.append(f"    .configureBreakDeadTime = {'true' if has_bdt else 'false'},")
    if has_bdt:
        body.append(f"    .breakDeadTime = {{ HW_TIM_CUBEMX_BDT_{name} }},")
    if has_brkin:
        body.append(f"    .breakInputs = {{ HW_TIM_CUBEMX_BRKIN_{name} }},")
    body.append(f"    .configureTrgo = {'true' if has_trgo else 'false'},")
    if has_trgo:
        body.append(f"    .master = {{ HW_TIM_CUBEMX_MASTER_{name} }},")
    return emit_macro(f"HW_TIM_CUBEMX_G4_PERIPH_{name}", body)


def gen_tim_sim_peripheral_macro(name: str, tim: TIMConfig, has_bdt: bool) -> str:
    init = dict(tim.init)
    inum = tim_instance_num(tim.instance)
    width = 32 if inum in TIM_32BIT_INSTANCES else 16
    body: list[str] = [
        f'    .nameStr          = "{tim.instance}",',
        f"    .prescaler        = {init.get('Prescaler', '0')}U,",
        f"    .period           = {init.get('Period', '0')}U,",
        f"    .counterWidthBits = {width}U,",
        f"    .countDir         = {sim_count_dir(init.get('CounterMode', ''))},",
    ]
    counts_per_us = sim_counts_per_us(inum, init.get('Prescaler', ''))
    if counts_per_us is None:
        print(f"  WARN: {tim.instance} prescaler {init.get('Prescaler', '?')} does not "
              f"divide {TIM_KERNEL_CLOCK_HZ} Hz into whole counts per microsecond; "
              f"its sim counter will not track sim time until "
              f"TIM_COUNTS_PER_US_OVERRIDE names a value.", file=sys.stderr)
    else:
        body.append(f"    .countsPerUs      = {counts_per_us}U,")
    if "RepetitionCounter" in init:
        body.append(f"    .rcr              = {init['RepetitionCounter']}U,")
    if has_bdt:
        bdt = dict(tim.bdt)
        break_on = bdt.get("BreakState", "") == "TIM_BREAK_ENABLE"
        body.append("    .configureBreakDeadTime = true,")
        body.append(f"    .deadTime               = {bdt.get('DeadTime', '0')}U,")
        body.append(f"    .hasBreakInput          = {'true' if break_on else 'false'},")
    trgo = tim_trgo_constant(tim)
    has_trgo = not trgo.endswith("_RESET")
    body.append(f"    .configureTrgo          = {'true' if has_trgo else 'false'},")
    if has_trgo:
        source = sim_trgo_source(trgo)
        body.append(f"    .trgoSource             = {source},")
        if source == "HW_TIM_TRGO_OC_MATCH":
            body.append(f"    .trgoOcUnit             = {sim_trgo_oc_unit(trgo)}U,")
    return emit_macro(f"HW_TIM_CUBEMX_SIM_PERIPH_{name}", body)


def gen_tim_macros(tims: list[TIMConfig],
                   complementary: set[tuple[int, int]]) -> str:
    parts: list[str] = []
    for tim in tims:
        name = tim.instance
        has_oc = bool(tim.oc_units)
        has_bdt = tim.bdt is not None
        has_brkin = bool(tim.break_inputs)
        has_trgo = not tim_trgo_constant(tim).endswith("_RESET")

        parts.append(f"// ----- {name} -----")
        parts.append("")
        parts.append(emit_macro(f"HW_TIM_CUBEMX_INIT_{name}",
                                aligned_assignments(tim.init, indent="    ")))
        parts.append("")
        if has_bdt:
            parts.append(emit_macro(f"HW_TIM_CUBEMX_BDT_{name}",
                                    aligned_assignments(tim.bdt, indent="    ")))
            parts.append("")
        if has_brkin:
            parts.append(gen_tim_break_input_macro(name, tim))
            parts.append("")
        if has_trgo:
            parts.append(emit_macro(f"HW_TIM_CUBEMX_MASTER_{name}",
                                    aligned_assignments(tim.master, indent="    ")))
            parts.append("")
        # Peripheral-plane body per target: everything instance-level, minus the
        # output-compare units. HW_TIM_channels.c maps each peripheral to one.
        parts.append(gen_tim_peripheral_macro(name, tim, has_bdt,
                                              has_brkin, has_trgo))
        parts.append("")
        parts.append(gen_tim_sim_peripheral_macro(name, tim, has_bdt))
        parts.append("")
        # Logical-channel-plane bodies: one per-output OC macro per target that
        # HW_TIM_channels.c references from each logical channel entry.
        if has_oc:
            parts.extend(gen_tim_oc_macros(name, tim, complementary))
            parts.extend(gen_tim_sim_oc_macros(name, tim, complementary))

    # Target selection: map each timer's neutral names (one peripheral body plus
    # one per output-compare unit) to their per-target bodies, so
    # HW_TIM_channels.c maps every plane uniformly with no BUILD_TARGET
    # branching of its own.
    parts.append("// ----- target selection -----")
    parts.append("")
    parts.append("#if (BUILD_TARGET == BUILD_TARGET_STM32G4)")
    for tim in tims:
        name = tim.instance
        parts.append(f"#define HW_TIM_CUBEMX_PERIPH_{name}  HW_TIM_CUBEMX_G4_PERIPH_{name}")
        for oc in tim.oc_units:
            chnum = tim_channel_num(oc.channel)
            parts.append(f"#define HW_TIM_CUBEMX_OC_{name}_CH{chnum}  "
                         f"HW_TIM_CUBEMX_G4_OC_{name}_CH{chnum}")
    parts.append("#elif (BUILD_TARGET == BUILD_TARGET_SIM)")
    for tim in tims:
        name = tim.instance
        parts.append(f"#define HW_TIM_CUBEMX_PERIPH_{name}  HW_TIM_CUBEMX_SIM_PERIPH_{name}")
        for oc in tim.oc_units:
            chnum = tim_channel_num(oc.channel)
            parts.append(f"#define HW_TIM_CUBEMX_OC_{name}_CH{chnum}  "
                         f"HW_TIM_CUBEMX_SIM_OC_{name}_CH{chnum}")
    parts.append("#else")
    parts.append('#error "BUILD_TARGET must be BUILD_TARGET_STM32G4 or BUILD_TARGET_SIM"')
    parts.append("#endif")
    parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_tim_header(tims: list[TIMConfig],
                     complementary: set[tuple[int, int]]) -> None:
    macros = gen_tim_macros(tims, complementary)
    content = (
        f"{file_header('cubemx_to_channels.py')}"
        f"\n"
        f"#ifndef HW_TIM_CHANNELS_CUBEMX_H\n"
        f"#define HW_TIM_CHANNELS_CUBEMX_H\n"
        f"\n"
        f"// Each timer exposes a per-target peripheral body\n"
        f"// (HW_TIM_CUBEMX_G4_PERIPH_TIMn / HW_TIM_CUBEMX_SIM_PERIPH_TIMn) plus\n"
        f"// one per-output body per output-compare unit\n"
        f"// (HW_TIM_CUBEMX_{{G4,SIM}}_OC_TIMn_CHm), each aliased by a\n"
        f"// BUILD_TARGET-selected name (HW_TIM_CUBEMX_PERIPH_TIMn /\n"
        f"// HW_TIM_CUBEMX_OC_TIMn_CHm) used by HW_TIM_channels.c. lib_build.h\n"
        f"// supplies the BUILD_TARGET_* constants the selection compares.\n"
        f'#include "lib_build.h"\n'
        f"\n"
        f"{macros}\n"
        f"#endif // HW_TIM_CHANNELS_CUBEMX_H\n"
    )
    TIM_OUT.write_text(content, encoding="utf-8")
    total_oc = sum(len(t.oc_units) for t in tims)
    print(f"  wrote {TIM_OUT.relative_to(REPO_ROOT)} "
          f"({len(tims)} TIMs, {total_oc} output-compare units)")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main() -> int:
    if not CUBEMX_MAIN.is_file():
        print(f"Error: {CUBEMX_MAIN} not found.", file=sys.stderr)
        return 1
    source = CUBEMX_MAIN.read_text(encoding="utf-8", errors="replace")

    # GPIO ------------------------------------------------------------
    gpio_body = extract_function_body(source, "MX_GPIO_Init")
    if gpio_body is None:
        print("  WARN: MX_GPIO_Init not found in cubemx main.c; "
              "skipping GPIO header.", file=sys.stderr)
    else:
        pins_by_port = parse_mx_gpio_init(gpio_body)
        if not pins_by_port:
            print("  WARN: no HAL_GPIO_Init calls parsed; "
                  "writing empty GPIO header.", file=sys.stderr)
        write_gpio_header(pins_by_port)

    # ADC -------------------------------------------------------------
    # Find every MX_ADCN_Init function (typically MX_ADC1_Init,
    # MX_ADC2_Init, ...) and parse each. Both the prototype and the
    # definition match `void NAME(void)`, so dedupe by name.
    adc_funcs_raw = re.findall(
        r'\bvoid\s+(MX_ADC(\d+)_Init)\s*\(\s*void\s*\)', source)
    adc_funcs = sorted(set(adc_funcs_raw), key=lambda x: int(x[1]))
    adcs: list[ADCConfig] = []
    for func_name, n in adc_funcs:
        body = extract_function_body(source, func_name)
        if body is None:
            continue
        cfg = parse_mx_adc_init(body, hadc_var=f"hadc{n}")
        if cfg is None:
            print(f"  WARN: couldn't parse {func_name}; skipping.",
                  file=sys.stderr)
            continue
        adcs.append(cfg)
    if not adcs:
        print("  WARN: no MX_ADC*_Init functions found; "
              "writing empty ADC header.", file=sys.stderr)
    write_adc_header(adcs)

    # SPI -------------------------------------------------------------
    # Find every MX_SPIN_Init function and parse its hspiN.Init.* block.
    spi_funcs_raw = re.findall(
        r'\bvoid\s+(MX_SPI(\d+)_Init)\s*\(\s*void\s*\)', source)
    spi_funcs = sorted(set(spi_funcs_raw), key=lambda x: int(x[1]))
    spis: list[SPIConfig] = []
    for func_name, n in spi_funcs:
        body = extract_function_body(source, func_name)
        if body is None:
            continue
        cfg = parse_mx_spi_init(body, hspi_var=f"hspi{n}")
        if cfg is None:
            print(f"  WARN: couldn't parse {func_name}; skipping.",
                  file=sys.stderr)
            continue
        spis.append(cfg)
    if not spis:
        print("  WARN: no MX_SPI*_Init functions found; "
              "writing empty SPI header.", file=sys.stderr)
    write_spi_header(spis)

    # TIM -------------------------------------------------------------
    # Complementary (CHxN) outputs are detectable only from the GPIO AF
    # routing in HAL_TIM_MspPostInit (in hal_msp.c), not from MX_TIM*_Init.
    msp_source = ""
    if CUBEMX_MSP.is_file():
        msp_source = CUBEMX_MSP.read_text(encoding="utf-8", errors="replace")
    else:
        print(f"  WARN: {CUBEMX_MSP.name} not found; complementary outputs "
              "will all read false.", file=sys.stderr)
    complementary = parse_complementary_channels(msp_source)

    tim_funcs_raw = re.findall(
        r'\bvoid\s+(MX_TIM(\d+)_Init)\s*\(\s*void\s*\)', source)
    tim_funcs = sorted(set(tim_funcs_raw), key=lambda x: int(x[1]))
    tims: list[TIMConfig] = []
    for func_name, n in tim_funcs:
        body = extract_function_body(source, func_name)
        if body is None:
            continue
        cfg = parse_mx_tim_init(body, htim_var=f"htim{n}")
        if cfg is None:
            print(f"  WARN: couldn't parse {func_name}; skipping.",
                  file=sys.stderr)
            continue
        tims.append(cfg)
    if not tims:
        print("  WARN: no MX_TIM*_Init functions found; "
              "writing empty TIM header.", file=sys.stderr)
    write_tim_header(tims, complementary)

    return 0


if __name__ == "__main__":
    sys.exit(main())
