// AUTO-GENERATED by tools/cubemx_to_channels.py from
// sw/fw/stm32cube/g4/Core/Src/main.c. Do not hand-edit.
//
// Re-generate via: tools/convert_cubemx_to_canonical.sh
//
// This file holds macros containing CubeMX-derived field values.
// The hand-written HW_*_channels.c references them inside its
// struct initializers; user-managed fields (triggerMode, vref,
// injectedInputs, ...) live there too, outside the macro
// expansions.

#ifndef HW_ADC_CHANNELS_CUBEMX_H
#define HW_ADC_CHANNELS_CUBEMX_H

// ----- ADC1 -----

#define HW_ADC_CUBEMX_HADC_INSTANCE_ADC1  ADC1

#define HW_ADC_CUBEMX_HADC_INIT_ADC1 \
    .ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4, \
    .Resolution            = ADC_RESOLUTION_12B, \
    .DataAlign             = ADC_DATAALIGN_RIGHT, \
    .GainCompensation      = 0, \
    .ScanConvMode          = ADC_SCAN_DISABLE, \
    .EOCSelection          = ADC_EOC_SINGLE_CONV, \
    .LowPowerAutoWait      = DISABLE, \
    .ContinuousConvMode    = DISABLE, \
    .NbrOfConversion       = 1, \
    .DiscontinuousConvMode = DISABLE, \
    .ExternalTrigConv      = ADC_SOFTWARE_START, \
    .ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE, \
    .DMAContinuousRequests = DISABLE, \
    .Overrun               = ADC_OVR_DATA_PRESERVED, \
    .OversamplingMode      = DISABLE,

#define HW_ADC_CUBEMX_MULTIMODE_ADC1 \
    .Mode = ADC_MODE_INDEPENDENT,

#define HW_ADC_CUBEMX_INPUTS_ADC1 \
    [6] = \
    { \
        .enabled = true, \
        .sConfig = \
        { \
            .Channel      = ADC_CHANNEL_6, \
            .Rank         = ADC_REGULAR_RANK_1, \
            .SamplingTime = ADC_SAMPLETIME_2CYCLES_5, \
            .SingleDiff   = ADC_SINGLE_ENDED, \
            .OffsetNumber = ADC_OFFSET_NONE, \
            .Offset       = 0, \
        }, \
    },

#define HW_ADC_CUBEMX_SIM_INPUTS_ADC1 \
    [6] = { .enabled = true, .inputNameStr = "ADC1_IN6" },

// ----- ADC2 -----

#define HW_ADC_CUBEMX_HADC_INSTANCE_ADC2  ADC2

#define HW_ADC_CUBEMX_HADC_INIT_ADC2 \
    .ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4, \
    .Resolution            = ADC_RESOLUTION_12B, \
    .DataAlign             = ADC_DATAALIGN_RIGHT, \
    .GainCompensation      = 0, \
    .ScanConvMode          = ADC_SCAN_DISABLE, \
    .EOCSelection          = ADC_EOC_SINGLE_CONV, \
    .LowPowerAutoWait      = DISABLE, \
    .ContinuousConvMode    = DISABLE, \
    .NbrOfConversion       = 1, \
    .DiscontinuousConvMode = DISABLE, \
    .ExternalTrigConv      = ADC_SOFTWARE_START, \
    .ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE, \
    .DMAContinuousRequests = DISABLE, \
    .Overrun               = ADC_OVR_DATA_PRESERVED, \
    .OversamplingMode      = DISABLE,

#define HW_ADC_CUBEMX_INPUTS_ADC2 \
    [11] = \
    { \
        .enabled = true, \
        .sConfig = \
        { \
            .Channel      = ADC_CHANNEL_11, \
            .Rank         = ADC_REGULAR_RANK_1, \
            .SamplingTime = ADC_SAMPLETIME_2CYCLES_5, \
            .SingleDiff   = ADC_SINGLE_ENDED, \
            .OffsetNumber = ADC_OFFSET_NONE, \
            .Offset       = 0, \
        }, \
    },

#define HW_ADC_CUBEMX_SIM_INPUTS_ADC2 \
    [11] = { .enabled = true, .inputNameStr = "ADC2_IN11" },

#endif // HW_ADC_CHANNELS_CUBEMX_H
