/* Includes */

#include "lib_types.h"
#include "lib_utils.h"
#include "lib_build.h"

#include "HW_ADC.h"
// HAL types in the BUILD_TARGET_STM32G4 branch (ADC_HandleTypeDef, ADC1,
// ADC_CHANNEL_6, etc.) come transitively through HW_ADC.h, which on the
// embedded target resolves to stm32g4/HW_ADC.h (which #includes
// stm32g4xx_hal.h). On the native target the elided branch is never
// parsed so no HAL include is needed.

// Auto-generated CubeMX-derived field values. Re-generated by
// tools/cubemx_to_channels.py (called from
// tools/convert_cubemx_to_canonical.sh) whenever the .ioc changes.
#include "HW_ADC_channels.cubemx.h"

/* Defines */

/* Typedefs */

/* Private Data Definitions */

const HW_ADC_channelConfig_S HW_ADC_channelConfig[HW_ADC_CHANNEL_COUNT] =
{
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
    [HW_ADC_CHANNEL_1] =
    {
        // ADC1: independent mode; injected U/V simultaneity comes from the
        // shared TIM1 TRGO2 hardware trigger, not a dual-ADC pairing.
        .hadc =
        {
            .Instance = HW_ADC_CUBEMX_HADC_INSTANCE_ADC1,
            .Init = { HW_ADC_CUBEMX_HADC_INIT_ADC1 },
        },

        .configureMultimode = true,
        .multimode = { HW_ADC_CUBEMX_MULTIMODE_ADC1 },

        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_TIMER,
        .injectedXferMode    = HW_ADC_XFER_INTERRUPT,
        .vref                = 3.3f,

        .inputs         =
        {
            HW_ADC_CUBEMX_INPUTS_ADC1   // macro supplies its own trailing comma
            // Hand-authored: the CubeMX converter does not emit VOPAMP
            // internal channels. OPAMP1 output -> ADC1 IN13, appended to
            // the regular sequence as rank 5 (cubemx claims ranks 1-4).
            [13] =
            {
                .enabled = true,
                .sConfig =
                {
                    .Channel      = ADC_CHANNEL_VOPAMP1,
                    .Rank         = ADC_REGULAR_RANK_5,
                    .SamplingTime = ADC_SAMPLETIME_47CYCLES_5,
                    .SingleDiff   = ADC_SINGLE_ENDED,
                    .OffsetNumber = ADC_OFFSET_NONE,
                    .Offset       = 0,
                },
            },
        },
        .injectedInputs =
        {
            [0] =
            {
                .enabled = true,
                .sConfig =
                {
                    .InjectedChannel = ADC_CHANNEL_6, // Phase U ISENSE
                    // injected rank inferred from 'injectedInputs' array index
                    .InjectedSamplingTime = ADC_SAMPLETIME_24CYCLES_5,
                    .InjectedSingleDiff = ADC_SINGLE_ENDED,
                    .InjectedOffsetNumber = ADC_OFFSET_NONE,
                    .InjectedOffset = 0,
                    .InjectedOffsetSign = ADC_OFFSET_SIGN_NEGATIVE,
                    .InjectedOffsetSaturation = DISABLE,
                }
            }
        },
        .injectedTimerTrigger = HW_ADC_TIMER_TRIGGER_TIM1_TRGO2,
        .injectedTriggerEdge = HW_ADC_TRIGGER_EDGE_RISING,
    },

    [HW_ADC_CHANNEL_2] =
    {
        // ADC2: independent mode, same shared-TRGO2 trigger as ADC1.
        .hadc =
        {
            .Instance = HW_ADC_CUBEMX_HADC_INSTANCE_ADC2,
            .Init = { HW_ADC_CUBEMX_HADC_INIT_ADC2 },
        },

        .configureMultimode = false,
        .multimode = { 0U },

        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_TIMER,
        .injectedXferMode    = HW_ADC_XFER_INTERRUPT,
        .vref                = 3.3f,

        .inputs         =
        {
            HW_ADC_CUBEMX_INPUTS_ADC2   // macro supplies its own trailing comma
            // Hand-authored: the CubeMX converter does not emit VOPAMP
            // internal channels. OPAMP2 output -> ADC2 IN16 (rank 4),
            // OPAMP3 output -> ADC2 IN18 (rank 5), appended to the regular
            // sequence after the cubemx-claimed ranks 1-3.
            [16] =
            {
                .enabled = true,
                .sConfig =
                {
                    .Channel      = ADC_CHANNEL_VOPAMP2,
                    .Rank         = ADC_REGULAR_RANK_4,
                    .SamplingTime = ADC_SAMPLETIME_47CYCLES_5,
                    .SingleDiff   = ADC_SINGLE_ENDED,
                    .OffsetNumber = ADC_OFFSET_NONE,
                    .Offset       = 0,
                },
            },
            [18] =
            {
                .enabled = true,
                .sConfig =
                {
                    .Channel      = ADC_CHANNEL_VOPAMP3_ADC2,
                    .Rank         = ADC_REGULAR_RANK_5,
                    .SamplingTime = ADC_SAMPLETIME_47CYCLES_5,
                    .SingleDiff   = ADC_SINGLE_ENDED,
                    .OffsetNumber = ADC_OFFSET_NONE,
                    .Offset       = 0,
                },
            },
        },
        .injectedInputs =
        {
            [0] =
            {
                .enabled = true,
                .sConfig =
                {
                    .InjectedChannel = ADC_CHANNEL_7, // Phase V ISENSE
                    // injected rank inferred from 'injectedInputs' array index
                    .InjectedSamplingTime = ADC_SAMPLETIME_24CYCLES_5,
                    .InjectedSingleDiff = ADC_SINGLE_ENDED,
                    .InjectedOffsetNumber = ADC_OFFSET_NONE,
                    .InjectedOffset = 0,
                    .InjectedOffsetSign = ADC_OFFSET_SIGN_NEGATIVE,
                    .InjectedOffsetSaturation = DISABLE,
                }
            }
        },
        .injectedTimerTrigger = HW_ADC_TIMER_TRIGGER_TIM1_TRGO2,
        .injectedTriggerEdge = HW_ADC_TRIGGER_EDGE_RISING,
    },

#elif (BUILD_TARGET == BUILD_TARGET_SIM)
    [HW_ADC_CHANNEL_1] =
    {
        .channelNameStr      = "ADC1",
        .configureMultimode  = true,
        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_SOFTWARE,
        .injectedXferMode    = HW_ADC_XFER_POLLED,
        .vref                = 3.3f,
        .numBits             = 12U,
        .inputs              =
        {
            HW_ADC_CUBEMX_SIM_INPUTS_ADC1   // macro supplies its own trailing comma
            // Hand-authored VOPAMP internal channel (see stm32g4 branch).
            [13] = { .enabled = true, .inputNameStr = "ADC1_VOPAMP1" },
        },
        .injectedInputs      = { { 0 } },
    },

    [HW_ADC_CHANNEL_2] =
    {
        .channelNameStr      = "ADC2",
        .configureMultimode  = false,
        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_SOFTWARE,
        .injectedXferMode    = HW_ADC_XFER_POLLED,
        .vref                = 3.3f,
        .numBits             = 12U,
        .inputs              =
        {
            HW_ADC_CUBEMX_SIM_INPUTS_ADC2   // macro supplies its own trailing comma
            // Hand-authored VOPAMP internal channels (see stm32g4 branch).
            [16] = { .enabled = true, .inputNameStr = "ADC2_VOPAMP2" },
            [18] = { .enabled = true, .inputNameStr = "ADC2_VOPAMP3" },
        },
        .injectedInputs      = { { 0 } },
    },
#else
#error "ERROR! HW_ADC_channelConfig not defined for build target!"
#endif
};

const HW_ADC_config_S HW_ADC_config =
{
    .channels    = HW_ADC_channelConfig,
    .numChannels = COUNTOF(HW_ADC_channelConfig),
};

/* Private Function Definitions */

/* Public Function Definitions */
