/* Includes */

#include "lib_types.h"
#include "lib_utils.h"
#include "lib_build.h"

#include "HW_ADC.h"
// HAL types in the BUILD_TARGET_STM32G4 branch (ADC_HandleTypeDef, ADC1,
// ADC_CHANNEL_6, etc.) come transitively through HW_ADC.h, which on the
// embedded target resolves to stm32g4/HW_ADC.h (which #includes
// stm32g4xx_hal.h). On the native target the elided branch is never
// parsed so no HAL include is needed.

// Auto-generated CubeMX-derived field values. Re-generated by
// tools/cubemx_to_channels.py (called from
// tools/convert_cubemx_to_canonical.sh) whenever the .ioc changes.
#include "HW_ADC_channels.cubemx.h"

/* Defines */

/* Typedefs */

/* Private Data Definitions */

const HW_ADC_channelConfig_S HW_ADC_channelConfig[HW_ADC_CHANNEL_COUNT] =
{
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
    [HW_ADC_CHANNEL_1] =
    {
        // ADC1: master of the ADC1+2 dual pair.
        .hadc =
        {
            .Instance = HW_ADC_CUBEMX_HADC_INSTANCE_ADC1,
            .Init = { HW_ADC_CUBEMX_HADC_INIT_ADC1 },
        },

        .configureMultimode = true,
        .multimode = { HW_ADC_CUBEMX_MULTIMODE_ADC1 },

        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_SOFTWARE,
        .injectedXferMode    = HW_ADC_XFER_POLLED,
        .vref                = 3.3f,

        .inputs         = { HW_ADC_CUBEMX_INPUTS_ADC1 },
        .injectedInputs = { { 0 } },  // No injected inputs configured yet.
                                  // FOC current sensing will put phase U on
                                  // this channel's slot 0, with ADC2's slot 0
                                  // = phase V, both triggered simultaneously
                                  // by TIM1 in dual-injected mode (multimode
                                  // becomes ADC_DUALMODE_INJECSIMULT). One
                                  // injected slot per ADC; the dual-mode
                                  // pairing is what gets the "exact same
                                  // instant" sampling that FOC needs.
    },

    [HW_ADC_CHANNEL_2] =
    {
        // ADC2: slave of the ADC1+2 dual pair.
        .hadc =
        {
            .Instance = HW_ADC_CUBEMX_HADC_INSTANCE_ADC2,
            .Init = { HW_ADC_CUBEMX_HADC_INIT_ADC2 },
        },

        .configureMultimode = false,
        .multimode = { 0U },

        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_SOFTWARE,
        .injectedXferMode    = HW_ADC_XFER_POLLED,
        .vref                = 3.3f,

        .inputs         = { HW_ADC_CUBEMX_INPUTS_ADC2 },
        .injectedInputs = { { 0 } },
    },

#elif (BUILD_TARGET == BUILD_TARGET_SIM)
    [HW_ADC_CHANNEL_1] =
    {
        .channelNameStr      = "ADC1",
        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_SOFTWARE,
        .injectedXferMode    = HW_ADC_XFER_POLLED,
        .vref                = 3.3f,
        .numBits             = 12U,
        .inputs              = { HW_ADC_CUBEMX_SIM_INPUTS_ADC1 },
        .injectedInputs      = { { 0 } },
    },

    [HW_ADC_CHANNEL_2] =
    {
        .channelNameStr      = "ADC2",
        .triggerMode         = HW_ADC_TRIGGER_SOFTWARE,
        .xferMode            = HW_ADC_XFER_POLLED,
        .injectedTriggerMode = HW_ADC_TRIGGER_SOFTWARE,
        .injectedXferMode    = HW_ADC_XFER_POLLED,
        .vref                = 3.3f,
        .numBits             = 12U,
        .inputs              = { HW_ADC_CUBEMX_SIM_INPUTS_ADC2 },
        .injectedInputs      = { { 0 } },
    },
#else
#error "ERROR! HW_ADC_channelConfig not defined for build target!"
#endif
};

const HW_ADC_config_S HW_ADC_config =
{
    .channels    = HW_ADC_channelConfig,
    .numChannels = COUNTOF(HW_ADC_channelConfig),
};

/* Private Function Definitions */

/* Public Function Definitions */
