// AUTO-GENERATED by tools/cubemx_to_channels.py from
// sw/fw/stm32cube/g4/Core/Src/main.c. Do not hand-edit.
//
// Re-generate via: tools/convert_cubemx_to_canonical.sh
//
// This file holds macros containing CubeMX-derived field values.
// The hand-written HW_*_channels.c references them inside its
// struct initializers; user-managed fields (triggerMode, vref,
// injectedInputs, ...) live there too, outside the macro
// expansions.

#ifndef HW_SPI_CHANNELS_CUBEMX_H
#define HW_SPI_CHANNELS_CUBEMX_H

// ----- SPI1 -----

#define HW_SPI_CUBEMX_INIT_SPI1 \
    .Mode              = SPI_MODE_MASTER, \
    .Direction         = SPI_DIRECTION_2LINES, \
    .DataSize          = SPI_DATASIZE_8BIT, \
    .CLKPolarity       = SPI_POLARITY_LOW, \
    .CLKPhase          = SPI_PHASE_2EDGE, \
    .NSS               = SPI_NSS_SOFT, \
    .BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32, \
    .FirstBit          = SPI_FIRSTBIT_MSB, \
    .TIMode            = SPI_TIMODE_DISABLE, \
    .CRCCalculation    = SPI_CRCCALCULATION_DISABLE, \
    .CRCPolynomial     = 7, \
    .CRCLength         = SPI_CRC_LENGTH_DATASIZE, \
    .NSSPMode          = SPI_NSS_PULSE_DISABLE,

// ----- SPI3 -----

#define HW_SPI_CUBEMX_INIT_SPI3 \
    .Mode              = SPI_MODE_MASTER, \
    .Direction         = SPI_DIRECTION_2LINES, \
    .DataSize          = SPI_DATASIZE_8BIT, \
    .CLKPolarity       = SPI_POLARITY_LOW, \
    .CLKPhase          = SPI_PHASE_1EDGE, \
    .NSS               = SPI_NSS_SOFT, \
    .BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32, \
    .FirstBit          = SPI_FIRSTBIT_MSB, \
    .TIMode            = SPI_TIMODE_DISABLE, \
    .CRCCalculation    = SPI_CRCCALCULATION_DISABLE, \
    .CRCPolynomial     = 7, \
    .CRCLength         = SPI_CRC_LENGTH_DATASIZE, \
    .NSSPMode          = SPI_NSS_PULSE_ENABLE,

#endif // HW_SPI_CHANNELS_CUBEMX_H
