// AUTO-GENERATED by tools/cubemx_to_channels.py from
// sw/fw/stm32cube/g4/Core/Src/main.c. Do not hand-edit.
//
// Re-generate via: tools/convert_cubemx_to_canonical.sh
//
// This file holds macros containing CubeMX-derived field values.
// The hand-written HW_*_channels.c references them inside its
// struct initializers; user-managed fields (triggerMode, vref,
// injectedInputs, ...) live there too, outside the macro
// expansions.

#ifndef HW_SPI_CHANNELS_CUBEMX_H
#define HW_SPI_CHANNELS_CUBEMX_H

// TODO

#endif // HW_SPI_CHANNELS_CUBEMX_H
