/* Includes */

#include "lib_types.h"
#include "lib_utils.h"
#include "lib_build.h"

#include "HW_SPI.h"

// Auto-generated CubeMX-derived field values. Re-generated by
// tools/cubemx_to_channels.py (called from
// tools/convert_cubemx_to_canonical.sh) whenever the .ioc changes.
#include "HW_SPI_channels.cubemx.h"

/* Defines */

/* Typedefs */

/* Private Data Definitions */


const HW_SPI_channelConfig_S HW_SPI_channelConfig[] =
{
    [HW_SPI_CHANNEL_1] =
    {
        .enabled = true,
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
        .hspi =
        {
            .Instance = SPI1,
            .Init =
            {
                .Mode = SPI_MODE_MASTER,
                .Direction = SPI_DIRECTION_2LINES,
                .DataSize = SPI_DATASIZE_4BIT,
                .CLKPolarity = SPI_POLARITY_LOW,
                .CLKPhase = SPI_PHASE_1EDGE,
                .NSS = SPI_NSS_SOFT,
                .BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2,
                .FirstBit = SPI_FIRSTBIT_MSB,
                .TIMode = SPI_TIMODE_DISABLE,
                .CRCCalculation = SPI_CRCCALCULATION_DISABLE,
                .CRCPolynomial = 7,
                .CRCLength = SPI_CRC_LENGTH_DATASIZE,
                .NSSPMode = SPI_NSS_PULSE_ENABLE,
            },
        },
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
        .channelNameStr      = "SPI1",
#else
# error "ERROR! HW_SPI_config not defined for build target!"
#endif
    },
    [HW_SPI_CHANNEL_2] =
    {
        .enabled = false,
    },
    [HW_SPI_CHANNEL_3] =
    {
        .enabled = true,
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
        .hspi =
        {
            .Instance = SPI3,
            .Init =
            {
                .Mode = SPI_MODE_MASTER,
                .Direction = SPI_DIRECTION_2LINES,
                .DataSize = SPI_DATASIZE_4BIT,
                .CLKPolarity = SPI_POLARITY_LOW,
                .CLKPhase = SPI_PHASE_1EDGE,
                .NSS = SPI_NSS_SOFT,
                .BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2,
                .FirstBit = SPI_FIRSTBIT_MSB,
                .TIMode = SPI_TIMODE_DISABLE,
                .CRCCalculation = SPI_CRCCALCULATION_DISABLE,
                .CRCPolynomial = 7,
                .CRCLength = SPI_CRC_LENGTH_DATASIZE,
                .NSSPMode = SPI_NSS_PULSE_ENABLE,
            },
        }
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
        .channelNameStr      = "SPI3",
#endif
    },
};


const HW_SPI_config_S HW_SPI_config =
{
    .channels = HW_SPI_channelConfig,
    .numChannels = COUNTOF(HW_SPI_channelConfig),
};

/* Private Function Definitions */

/* Public Function Definitions */
