/* Includes */

#include "lib_types.h"
#include "lib_utils.h"
#include "lib_build.h"

#include "HW_SPI.h"

// Auto-generated CubeMX-derived field values. Re-generated by
// tools/cubemx_to_channels.py (called from
// tools/convert_cubemx_to_canonical.sh) whenever the .ioc changes.
#include "HW_SPI_channels.cubemx.h"

/* Defines */

/* Typedefs */

/* Private Data Definitions */


const HW_SPI_busConfig_S HW_SPI_busConfig[] =
{
    [HW_SPI_BUS_1] =
    {
        .enabled = true,
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
        .hspi =
        {
            .Instance = SPI1,
            .Init =
            {
                .Mode = SPI_MODE_MASTER,
                .Direction = SPI_DIRECTION_2LINES,
                // AS5048 encoder: 16-bit frames sent as 8-bit byte pairs;
                // SPI mode 1 (CPOL=0/CPHA=1 — samples MOSI on the falling
                // edge, updates MISO on the rising edge, datasheet p.10);
                // TCLK >= 100ns (10 MHz max), so /32 of PCLK2 (144 MHz) =
                // 4.5 MHz keeps a comfortable margin.
                .DataSize = SPI_DATASIZE_8BIT,
                .CLKPolarity = SPI_POLARITY_LOW,
                .CLKPhase = SPI_PHASE_2EDGE,
                .NSS = SPI_NSS_SOFT,
                .BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32,
                .FirstBit = SPI_FIRSTBIT_MSB,
                .TIMode = SPI_TIMODE_DISABLE,
                .CRCCalculation = SPI_CRCCALCULATION_DISABLE,
                .CRCPolynomial = 7,
                .CRCLength = SPI_CRC_LENGTH_DATASIZE,
                .NSSPMode = SPI_NSS_PULSE_ENABLE,
            },
        },
        .transferMode = HW_SPI_TRANSFERMODE_SW,
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
        .transferMode    = HW_SPI_TRANSFERMODE_SW,
        .busNameStr      = "SPI1",
#else
# error "ERROR! HW_SPI_config not defined for build target!"
#endif
    },
    [HW_SPI_BUS_2] =
    {
        .enabled = false,
    },
    [HW_SPI_BUS_3] =
    {
        .enabled = true,
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
        .hspi =
        {
            .Instance = SPI3,
            .Init =
            {
                .Mode = SPI_MODE_MASTER,
                .Direction = SPI_DIRECTION_2LINES,
                .DataSize = SPI_DATASIZE_4BIT,
                .CLKPolarity = SPI_POLARITY_LOW,
                .CLKPhase = SPI_PHASE_1EDGE,
                .NSS = SPI_NSS_SOFT,
                .BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2,
                .FirstBit = SPI_FIRSTBIT_MSB,
                .TIMode = SPI_TIMODE_DISABLE,
                .CRCCalculation = SPI_CRCCALCULATION_DISABLE,
                .CRCPolynomial = 7,
                .CRCLength = SPI_CRC_LENGTH_DATASIZE,
                .NSSPMode = SPI_NSS_PULSE_ENABLE,
            },
        },
        .transferMode = HW_SPI_TRANSFERMODE_DMA,
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
        .transferMode    = HW_SPI_TRANSFERMODE_DMA,
        .busNameStr      = "SPI3",
#endif
    },
};

static const HW_SPI_channelConfig_S HW_SPI_channelConfig[] =
{
    [HW_SPI_CHANNEL_AS5048_1] =
    {
        .bus = HW_SPI_BUS_1,
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
        .csMode = HW_SPI_CS_MODE_GPIO,
        .csGpioConfig =
        {
            // ENC_SPI_CS0 = PC4 (GPIO_PIN_4 = 0x10), per micro.kicad_sch U8.21.
            .port = HW_GPIO_PORT_C,
            .pin = GPIO_PIN_4,
            .activeLevel = HW_GPIO_LEVEL_LOW,
        },
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
        .csMode = HW_SPI_CS_MODE_GPIO,
        .csGpioConfig =
        {
            // GPIO_PIN_4 (0x10); the HAL pin macros don't exist on native.
            .port = HW_GPIO_PORT_C,
            .pin = 0x10U,
            .activeLevel = HW_GPIO_LEVEL_LOW,
        },
        .channelNameStr      = "AS5048_1",
#endif
    },
    [HW_SPI_CHANNEL_AS5048_2] =
    {
        .bus = HW_SPI_BUS_1,
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
        .csMode = HW_SPI_CS_MODE_GPIO,
        .csGpioConfig =
        {
            // ENC_SPI_CS1 = PB2 (GPIO_PIN_2 = 0x04), per micro.kicad_sch U8.25.
            .port = HW_GPIO_PORT_B,
            .pin = GPIO_PIN_2,
            .activeLevel = HW_GPIO_LEVEL_LOW,
        },
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
        .csMode = HW_SPI_CS_MODE_GPIO,
        .csGpioConfig =
        {
            // GPIO_PIN_2 (0x04); the HAL pin macros don't exist on native.
            .port = HW_GPIO_PORT_B,
            .pin = 0x04U,
            .activeLevel = HW_GPIO_LEVEL_LOW,
        },
        .channelNameStr      = "AS5048_2",
#endif
    },
    [HW_SPI_CHANNEL_SK6805_STRING] =
    {
        .bus = HW_SPI_BUS_3,
#if (BUILD_TARGET == BUILD_TARGET_STM32G4)
        .csMode = HW_SPI_CS_MODE_NONE,
#elif (BUILD_TARGET == BUILD_TARGET_SIM)
        .csMode = HW_SPI_CS_MODE_NONE,
        .channelNameStr      = "SK6805_STRING",
#endif
    },
};


const HW_SPI_config_S HW_SPI_config =
{
    .buses = HW_SPI_busConfig,
    .numBuses = COUNTOF(HW_SPI_busConfig),

    .channels = HW_SPI_channelConfig,
    .numChannels = COUNTOF(HW_SPI_channelConfig),
};

/* Private Function Definitions */

/* Public Function Definitions */
